version = 1

exclude_patterns = [
  "dist/**",
  "*/forecast.egg-info/"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  skip_doc_coverage = ["module", "magic", "init", "class"]
  runtime_version = "3.x.x"
